site_name: Cloud Lab Chronicles
site_url: https://matthewww.github.io/cloud-lab-chronicles/
docs_dir: ../docs
nav:
  - Home: index.md
  - Labs: labs/00-pages-setup.md

theme:
  name: material

plugins:
  - search
  - awesome-pages
