name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: List files in the repository
      run: ls -la cloud-lab-chronicles/site
    - name: List files in the repository site
      run: ls -la site
    - name: List files in the repository ..
      run: ls -la ../../site

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material

    - name: Deploy to GitHub Pages
      run: |
        mkdocs gh-deploy --config-file /site/mkdocs.yml --force
